Ansible inventory support. Refactoring

diff --git a/bin/scu b/bin/scu
--- a/bin/scu
+++ b/bin/scu
@@ -3,121 +3,179 @@
 #
 # SSH Connection Utility (SCU)
 # - ssh connection utility with pre-defined hosts list
-#
-# You can run this script without parameters to get usage instructions - all you need will be displayed and no harmful activities will be done.
-#
-# Author: keir@keir.ru
+# https://github.com/dualmi/scu
 #
 # This project is licensed under GPL 3 License - see [https://www.gnu.org/licenses/gpl-3.0.en.html]
 #
 
 declare -A sshhostlist;
-HOSTSFILE="$HOME/.scurc";
+hosts_file="$HOME/.scurc";
+_bash=$(which bash)
 
-echo "";
-echo -e "\tSSH Connection Utility with predefined hosts list";
-echo "";
+echo -e "\n\tSSH Connection Utility with predefined hosts list\n";
 
 # Hosts file check part.
 # If file doesn't exists it can be generated when 'init' param is set.
-if [[ -f $HOSTSFILE ]]; then
- source $HOSTSFILE
+if [[ -f $hosts_file ]]; then
+  # shellcheck source=.scurc
+  source "$hosts_file"
 else
- if [[ $1 = "init" ]]; then
-  # At next step example config file will be generated
-  echo -e "# Array entry format:\n# [host-useful-name]=\"username server.address.or.ip ssh-port-if-not-default id_rsa_key_path-if-not-.ssh/id_rsa\"\n\nsshhostlist=(\n\t[example-host-one]=\"sshuser host-one.domain.local\"\n\t[example-host-two]=\"root host-two.domain.local 2222\"\n\t[example-line-one]=\"games server.domain.local 22\"\n\t[example-ext-host]=\"admin h24.contoso.com 22022 ~/.ssh/id_rsa_for_contoso\"\n);" > $HOSTSFILE
-  if [[ $? -eq 0 ]]; then
-   echo "Example config file $HOSTSFILE generated.";
-   echo "Edit it as you wish.";
-   echo "";
+  if [[ $1 = "init" ]]; then
+    # At next step example config file will be generated
+cat > "$hosts_file" <<EOL
+# Array entry format:
+# [host-useful-name]="username* server.address.or.ip* ssh-port-if-not-default other-ssh-arguments"
+# * - is required
+
+# If you'll set the path to ansible host file(s), ansible hosts will be loaded firstly.
+# Hosts with the same names will be overwritten (from the last loaded inventory file)
+
+# yq - https://github.com/mikefarah/yq - must be installed if you using an ansible inventory
+
+# You could point several space separated inventory files
+ansiblepath="
+$HOME/.scurc.yaml
+/wrong/file/name
+"
+
+sshhostlist=(
+  # here is 4 examples to show how it will be shown in terminal
+  # while you just run 'scu' w/o parameters or
+  # type only part of host name like 'scu host'
+  [example-host-one]="sshuser host-one.domain.local"
+  [example-host-two]="root host-two.domain.local 2222"
+  [example-line-one]="games server.domain.local 22"
+  [example-ext-host]="admin h24.contoso.com 22022 -i ~/.ssh/id_rsa_for_contoso"
+);
+EOL
+
+cat > "$hosts_file.yaml" <<EOL
+# Here is the inventory example which could be used by Ansible and scu
+all:
+  children:
+    my_company:
+      vars:
+        ansible_user: root
+        ansible_port: 22
+      children:
+        firstgroup:
+          hosts:
+            example-host-yaml:
+              ansible_host: 192.168.1.1
+            example-host-yaml-args:
+              ansible_user: admin
+              ansible_host: 192.168.2.2
+              ansible_port: 3333
+              ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ssh-tunnel@10.10.2.2 -p 2222"'
+EOL
+
+    echo "Example config files $hosts_file and $hosts_file.yaml are generated.";
+    echo -e "Edit them as you wish.\n";
+    exit 0;
   fi
-  exit 0;
- fi
- echo "File with list of ssh hosts ($HOSTSFILE) not found. No way to live.";
- echo "(!) You can initialize example file - run '$0 init' to do that.";
- echo "";
- exit 1;
+  echo "File with list of ssh hosts ($hosts_file) not found. No way to live.";
+  echo "(!) You can initialize example file - run '$0 init' to do that.";
+  echo "";
+  exit 1;
+fi
+
+# # If path to ansible host file (yaml format) is set, then using it and updating original list from .scurc
+if [[ $ansiblepath ]]; then
+  if [[ $(yq --version | awk '{ print $NF }' | sed -e 's,^[^0-9]\([0-9]*\).*,\1,g') -lt 4 ]]; then
+    echo -e "Your yq version not suitable for this script\n please install the latest version from https://github.com/mikefarah/yq"
+  fi
+  for inventory in $ansiblepath; do
+    if [[ -r $inventory ]]; then
+      OLDIFS=$IFS
+      IFS=$'\n'
+      for line in $(
+        yq -r '.all.children.* as $company
+          | $company.children.*.*
+          | to_entries
+          | .[]
+          | [{.key: (.value.ansible_user // $company.vars.ansible_user // "root")
+           + " " + .value.ansible_host + " " + (.value.ansible_port // $company.vars.ansible_port // 22)
+           + " " + (.value.ansible_ssh_common_args // $company.vars.ansible_ssh_common_args // "")}]
+          | .[]' $inventory | sed -e 's,"$,,;s,",,;s,\\",",g' | grep -E -v '^#'
+        ); do
+          sshhostlist["${line%%:*}"]=${line#*:}
+      done
+      IFS=$OLDIFS
+    else
+      echo -e "\n! Path $inventory is set in ansiblepath variable, but file is not readable!\n! Either clear this or specify the correct path\n"
+    fi
+  done
 fi
 
 # Indexing hosts list. After that connection by host number will be available.
-declare -A ARRINDEX;
-ARRITER=1;
+declare -A array_index;
+array_i=1;
 for value in "${!sshhostlist[@]}"; do
- ARRINDEX[$value]=$ARRITER;
- let ARRITER=ARRITER+1;
+  array_index[$value]=$array_i;
+  array_i=$(( array_i+1 ))
 done
 
 # Connecting to host if exists
-CONHOST=$1
-for value in "${!sshhostlist[@]}"; do
- if [[ $value = $CONHOST ]] || [[ ${ARRINDEX[$value]} = $CONHOST ]]; then
-  USERNAME=$(echo -n ${sshhostlist[$value]}|awk '{ print $1 }');
-  ADDRESS=$(echo -n ${sshhostlist[$value]}|awk '{ print $2 }');
-  PORT=$(echo -n ${sshhostlist[$value]}|awk -v ORS="" '{ print $3; if ($3=="") printf "%s","22" }');
-  PRIVKEY=$(echo -n ${sshhostlist[$value]}|awk -v ORS="" -v HOME="$HOME" '{ print $4; if ($4=="") printf HOME "%s","/.ssh/id_rsa" }');
-  # Tilde expansion didn't work in IF statement if quoted in variable, so convert it to HOME here
-  PRIVKEY=$(echo $PRIVKEY | sed -e "s,^~,$HOME,");
-  if [[ -r $PRIVKEY ]]; then
-    echo "Connecting to $value with user '$USERNAME', address '$ADDRESS' and port '$PORT' with key '$PRIVKEY'...";
-    PRIVKEY="-i $PRIVKEY"
-  else
-    echo "Connecting to $value with user '$USERNAME', address '$ADDRESS' and port '$PORT' without key...";
-    PRIVKEY=''
+host_connect=$1
+for sshhost in "${!sshhostlist[@]}"; do
+  if [[ $sshhost = "$host_connect" ]] || [[ ${array_index[$sshhost]} = "$host_connect" ]]; then
+    USERNAME=$(echo -n "${sshhostlist[$sshhost]}"|awk '{ print $1 }');
+    ADDRESS=$(echo -n "${sshhostlist[$sshhost]}"|awk '{ print $2 }');
+    PORT=$(echo -n "${sshhostlist[$sshhost]}"|awk -v ORS="" '{ print $3; if ($3=="") printf "%s","22" }');
+    SSHARGS=$(echo -n "${sshhostlist[$sshhost]}"|awk '{ if ($4) print substr($0, index($0,$4)) }');
+    echo -n "Connecting to $sshhost with command: ";
+    $_bash -x -c "ssh -p $PORT $SSHARGS $USERNAME@$ADDRESS"
+    exit 0;
   fi
-  echo "";
-  ssh $USERNAME@$ADDRESS -p $PORT $PRIVKEY
-  exit 0;
- fi
 done
 
 #
 # Usage information and hosts list
 # which will be displayed if no valid host was choosen
 #
- echo -e "\t\tUsage: $0 <host number|host name>";
- echo "";
- echo "Available hosts:";
- COUNTER=1;
- COUNTER2=1;
- for value in "${!sshhostlist[@]}"; do
+echo -e "\t\tUsage: $0 <host number|host name>\n";
+echo "Available hosts:";
+counter=1;
+counter2=1;
+for value in "${!sshhostlist[@]}"; do
   name="$value";
-  value="${ARRINDEX[$value]}: $value";
+  value="${array_index[$value]}: $value";
   if [[ ${#value} -gt 7 ]]; then
-   if [[ ${#value} -gt 15 ]]; then
-    RES="$value\t";
-   else
-    RES="$value\t\t";
-   fi
+    if [[ ${#value} -gt 15 ]]; then
+      RES="$value\t";
+    else
+      RES="$value\t\t";
+    fi
   else
-   RES="$value\t\t\t";
+    RES="$value\t\t\t";
   fi
-  if [[ ! -z $CONHOST ]]; then
-   [[ $RES =~ $CONHOST ]] || continue;
-   MATCHVALUE="$name";
-   echo -ne "$RES";
+  if [[ -n $host_connect ]]; then
+    [[ $RES =~ $host_connect ]] || continue;
+    MATCHVALUE="$name";
+    echo -ne "$RES";
   else
-   echo -ne "$RES";
+    echo -ne "$RES";
   fi
-  let COUNTER=COUNTER+1;
-  let COUNTER2=COUNTER2+1;
-  if [[ $COUNTER -gt 3 ]]; then
-   echo "";
-   COUNTER=1;
+  counter=$(( counter+1 ))
+  counter2=$(( counter2+1 ))
+  if [[ $counter -gt 3 ]]; then
+    echo "";
+    counter=1;
   fi
- done
- echo "";
- if [ $COUNTER2 -eq 2 ] && [ ! -z $MATCHVALUE ]; then
+done
+echo "";
+if [ $counter2 -eq 2 ] && [ -n "$MATCHVALUE" ]; then
   echo "Connecting to only one matched host $MATCHVALUE...";
-  $0 $MATCHVALUE;
+  $0 "$MATCHVALUE";
   exit 0;
- fi
- if [ ! -z $CONHOST ] && [ $COUNTER2 -eq 1 ]; then
+fi
+if [ -n "$host_connect" ] && [ $counter2 -eq 1 ]; then
   echo "There is no host to connect with name you wrote...";
- fi
- echo "";
- if [ ! -z $CONHOST ] && [ $COUNTER2 -gt 1 ]; then
+fi
+echo "";
+if [ -n "$host_connect" ] && [ $counter2 -gt 1 ]; then
   echo -n "Enter host number / host name to connect: "
-  read input
-  $0 $input
+  read -r input
+  $0 "$input"
   exit 0;
- fi
+fi
